baseURL = "https://phucam.tv/"
languageCode = "vi"
title = "Phúc Âm"
removePathAccents = true
[pagination]
  pagerSize = 20

[params]
  description = "Phúc Âm TV"

[permalinks]
  [permalinks.page]
    articles = "/:sections/:slug/"
    doctrines = "/tin-ly/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreFiles = ['\.py$', 'output/']

[taxonomies]
  tag = "tags"
